
language: haskell
sudo: false

git:
  submodules: false  # whether to recursively clone submodules

cache:
  directories:
  - $HOME/.ghc

branches:
  only:
    - master

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.0.2

ghc:
  - "8.0.2"
script:
  - ghc zippy.hs src/*.hs -O -hidir compiled -odir compiled
